version: "3.9"

services:
  gaia_r:
    container_name: gaia-r
    build: ./R/
    image: gaia_r
    ports:
      - "8000:8000"
    networks:
      - gaiadb
  gaia_repo:
    container_name: gaia-repo
    build: ./searchApp/
    image: gaia_repo
    ports:
      - "5000:5000"
    networks:
      - gaiadb
    links:
      - "gaia_solr:index"
      - "gaia_r:gaiaCore"
  gaia_solr:
    container_name: gaia-solr
    image: solr
    networks:
      - gaiadb
    ports:
      - "8983:8983"
    volumes:
      - ./collections:/collections
      - solr-data:/var/solr

volumes:
  solr-data:
    name: gaia-solr-index

networks:
  gaiadb:
    name: gaiadb
    external: true